runtime: nodejs10
service: default
env_variables:
  NODE_ENV: production
  GRAPHQL: https://graphql-dot-crossfit-wod-0.appspot.com/

handlers:
  - url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
    static_files: dist/\1
    upload: dist/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    expiration: '15m'
